### ISSUE TITLE
issue with qt5

### ISSUE THREAD

**Issue by ericsia** [rsachetto/valkyrie-qt5#1]
I already run `sudo apt-get install qt5*-dev` and `sudo apt-get install qt5-default` but I get
`qmake: could not exec '/usr/lib/qt5/bin/qmake': No such file or directory`

can you kindly attach the deb in the release please?

**Comment by rsachetto** [comment]
Sorry, I did not see your issue before. I think you have to install qt5-qmake in order to compile.
